import {icon} from './icons.mjs';

export const esc = s => String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
export const link = (text, href, kind='') => `<a class="button ${kind}" href="${esc(href)}">${text}${icon('diagonal')}</a>`;
export const action = (text, key, settings, kind='') => settings[key] ? link(text, settings[key], kind) : `<button class="button ${kind}" data-unavailable="${key}">${text}${icon('diagonal')}</button>`;
export const label = (name, num) => `<div class="section-label"><span>${num ? `<span class="index">${num}</span>` : ''}${name}</span></div>`;
export const brand = () => `<a class="brand" href="/" aria-label="Unicorp Studio home"><span class="brand-word">unicorp<span>studio</span></span><span class="brand-dot" aria-hidden="true"></span></a>`;

export function header(os) {
  const nav = os ? `<a href="/">For businesses</a><a href="#the-workflow">The workflow</a><a href="#the-program">The program</a><a href="#pricing">Pricing</a>` : `<a href="#problem">The problem</a><a href="#how-it-works">How it works</a><a href="#offer">The offer</a><a href="/designeros/">DesignerOS${icon('diagonal')}</a>`;
  return `<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="header-inner">${brand()}<nav id="main-nav" aria-label="Main navigation">${nav}</nav><div class="header-actions">${link(os ? 'View pricing' : 'Book a call', os ? '#pricing' : '#contact', 'header-cta')}<button class="menu-toggle" aria-controls="main-nav" aria-expanded="false" aria-label="Open menu">Menu${icon('plus')}</button></div></div><div class="reading-progress" aria-hidden="true"></div></header>`;
}

export function hero(os, settings) {
  const heading = os ? 'Design it.<br>Build it.<br><em>Ship it.</em>' : 'We turn your brand into a scalable system your team — and AI — can actually use.';
  const description = os ? 'Learn the workflow to take an idea from design to a real production website with AI — without becoming a full-time developer.' : 'Strategy, identity, design and code brought together in one clear system — then applied to a website that is built to last.';
  return `<section class="hero ${os ? 'hero-os' : 'hero-agency'}" aria-labelledby="hero-title"><div class="hero-main"><div class="hero-kicker"><span class="index">${os ? '02' : '01'}</span><span>${os ? 'DesignerOS / an Unicorp Studio program' : 'AI-Ready Brand System'}</span></div><h1 id="hero-title">${heading}</h1><p class="hero-description">${description}</p><div class="hero-actions">${action(os ? 'Join DesignerOS' : 'Book a call', os ? 'checkoutUrl' : 'bookingUrl', settings)}${link(os ? 'Explore the program' : 'See how it works', os ? '#the-program' : '#how-it-works', 'button-outline')}</div><p class="hero-note">${os ? 'Built for designers who want more control over what they create.' : 'No long agency process. No messy handoff. No platform lock-in.'}</p></div><div class="hero-art"><div class="art-frame"><img src="/assets/system-object.jpg" alt="Abstract modular black and lime structure" width="1536" height="1024" fetchpriority="high"><div class="art-overlay"><span>${os ? 'DESIGNEROS — 01 / 07' : 'AI-READY BRAND SYSTEM'}</span><span>${icon('diagonal')}</span></div></div><div class="hero-art-caption"><span>${os ? 'FROM IDEA TO REAL PRODUCT' : 'STRATEGY · IDENTITY · CODE'}</span><span class="scroll-marker">Scroll to explore ↓</span></div></div><div class="hero-ticker" aria-label="Studio highlights"><span>${os ? 'DESIGN + SYSTEMS + AI + CODE + BUSINESS' : 'ONE SYSTEM · ONE SOURCE OF TRUTH'}</span><span>${os ? 'A PRACTICAL WORKFLOW' : 'BUILT TO LAST'}</span></div></section>`;
}

export function footer(os, settings) {
  const nav = os ? `<a href="/">AI-Ready Brand System</a><a href="#the-program">The program</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a>` : `<a href="#work">Projects</a><a href="#how-it-works">How it works</a><a href="#offer">The offer</a><a href="/designeros/">DesignerOS</a>`;
  return `<section class="contact-section" id="contact"><div class="contact-kicker">{ ${os ? 'Let’s build the workflow' : 'Let’s talk'} }</div><div class="contact-grid"><h2>${os ? 'Stop collecting tools.<br><em>Start shipping work.</em>' : 'If your brand is getting harder to manage,<br><em>let’s talk.</em>'}</h2><div class="contact-copy"><p>${os ? 'One program. Everything included. €690.' : 'Tell me what you’re working on and I’ll tell you if this approach makes sense.'}</p>${action(os ? 'Join DesignerOS' : 'Book a call', os ? 'checkoutUrl' : 'bookingUrl', settings, 'button-dark')}<small>${os ? 'The price will go up as the program gets better. No fake countdown timer.' : 'No hard sell. If we’re not a good fit, I’ll tell you.'}</small></div></div></section><footer class="site-footer"><div class="footer-top">${brand()}<div class="footer-intro">Strategy, identity, design<br>and code in one system.</div><nav aria-label="Footer navigation">${nav}</nav></div><div class="footer-wordmark" aria-hidden="true">unicorp<span>®</span></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Unicorp Studio</span><span>AI-Ready Brand System · DesignerOS</span></div></footer>`;
}

export const dialog = () => `<dialog id="availability" aria-labelledby="dialog-title" aria-describedby="dialog-copy"><button class="dialog-close" aria-label="Close dialog">${icon('cross')}</button>${label('Unicorp Studio')}<h2 id="dialog-title"></h2><p id="dialog-copy"></p><button class="button dialog-dismiss">Got it${icon('check')}</button></dialog>`;
